name: builder

on:
  workflow_dispatch:
  push:

jobs:
  jazzy:
    runs-on: ubuntu-24.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: jazzy
          DEB_DISTRO: noble
          ROSDEP_SOURCE: "yaml https://github.com/nobleo/ros_debian_packages/raw/main/rosdep/source.yaml"
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} only on main branch
          GITHUB_TOKEN: "${{ github.ref == 'refs/heads/main' && secrets.GITHUB_TOKEN || '' }}"
          REPOS_FILE: jazzy.repos
          GIT_LFS: true
          SBUILD_CONF: '$enable_network = 1;'  # For rmw_zenoh and novatel
        env:
          CARGO_HOME: /home/runner
