name: builder

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '13 2 * * *'  # Every day at 02:13 UTC

env:  # Only set the github token on the main branch on push events. Otherwise only build is verified but no binaries pushed
  EFFECTIVE_GITHUB_TOKEN: ${{ (github.event_name != 'schedule' && github.ref == 'refs/heads/main') && secrets.GITHUB_TOKEN || '' }}

jobs:
  jazzy:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/ros-infrastructure/bloom/pull/643
      # - uses: jspricke/ros-deb-builder-action@main
      - uses: nobleo/ros-deb-builder-action@debian-compat-13
        with:
          ROS_DISTRO: jazzy
          DEB_DISTRO: noble
          ROSDEP_SOURCE: "yaml https://github.com/nobleo/ros_debian_packages/raw/main/rosdep/source.yaml"
          COLCON_DEFAULTS_FILE: ${{ github.workspace }}/colcon_jazzy.yaml
          GITHUB_TOKEN: "${{ env.EFFECTIVE_GITHUB_TOKEN }}"
          REPOS_FILE: jazzy.repos
          GIT_LFS: true
          SBUILD_CONF: '$enable_network = 1;'  # For rmw_zenoh and novatel

  kilted:
    runs-on: ubuntu-24.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: kilted
          DEB_DISTRO: noble
          ROSDEP_SOURCE: "yaml https://github.com/nobleo/ros_debian_packages/raw/main/rosdep/source.yaml"
          COLCON_DEFAULTS_FILE: ${{ github.workspace }}/colcon_kilted.yaml
          GITHUB_TOKEN: "${{ env.EFFECTIVE_GITHUB_TOKEN }}"
          REPOS_FILE: rolling.repos
          GIT_LFS: true
          SBUILD_CONF: '$enable_network = 1;'  # For rmw_zenoh and novatel

  rolling:
    runs-on: ubuntu-24.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: rolling
          DEB_DISTRO: noble
          ROSDEP_SOURCE: "yaml https://github.com/nobleo/ros_debian_packages/raw/main/rosdep/source.yaml"
          COLCON_DEFAULTS_FILE: ${{ github.workspace }}/colcon_kilted.yaml
          GITHUB_TOKEN: "${{ env.EFFECTIVE_GITHUB_TOKEN }}"
          REPOS_FILE: rolling.repos
          GIT_LFS: true
          SBUILD_CONF: '$enable_network = 1;'  # For rmw_zenoh and novatel
