name: builder

on:
  workflow_dispatch:
  push:

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      # - uses: jspricke/ros-deb-builder-action@main until: https://github.com/jspricke/ros-deb-builder-action/issues/38
      - uses: christianrauch/ros-deb-builder-action@5befeabf68aad37cd1e3c594bbb13fe3f4b83de3
        with:
          ROS_DISTRO: iron
          DEB_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS_FILE: iron.repos
          GIT_LFS: true
          ROSDEP_SOURCE: yaml https://raw.githubusercontent.com/nobleo/ros_debian_packages/jammy-iron/local.yaml iron
